### ISSUE TITLE
Fix LogRus import

### ISSUE THREAD

**Issue by c0ze** [iron-io/runner#40]
logrus changed their repo case from `Sirupsen/logrus` to `sirupsen/logrus`

this is breaking a lot of projects. uppercase import still works, but the problem is you can not mix-match cases in your vendor tree. Unfortunately docker has adopted lower case import and this is preventing functions to resolve dependencies correctly.

https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276

I think we will have to eventually embrace the lowercase import as well. I was wondering if we can start with the runner, and how much stuff will this break ?

**Comment by c0ze** [comment]
@BupycHuk @rkononov

**Comment by vasilev** [comment]
@c0ze , feel free to update the runner. No negative influence is expected.
